version: '3.7'
services:

  logparserapp:
    image: node:16-alpine
    container_name: logparserapp      
    working_dir: /app
    tty: true
    volumes:
      - "./:/app"      
    networks:
      - default-network

networks:
    default-network:
      driver: bridge